### ISSUE TITLE
Buttons, please

### ISSUE THREAD

**Issue by beefoo** [NYPL/design#5]
it would also be nice to have `$buttonbackgroundcolor` and `$buttontextcolor` variables

**Comment by EdwinGuzman** [comment]
To add to the above, some WCAG 2.0 AA tools complain about having either foreground or background color defined but not the other, so it's good to have both defined for elements like the button.

**Comment by ricardoom** [comment]
Ok. commencing work on this issue.

**Comment by mgiraldo** [comment]
we should amend the `simple-button` mixin in `_forms.scss` to accept background colors, and use the defaults @beefoo is requesting

**Comment by ricardoom** [comment]
@mgiraldo working on this presently.

**Comment by mgiraldo** [comment]
moved to https://github.com/NYPL/design-toolkit/issues/5
