### ISSUE TITLE
Link color for link-heavy pages

### ISSUE THREAD

**Issue by beefoo** [NYPL/design#6]
We've received some feedback for pages that have a lot of links (e.g. a search results page), that the red is very overwhelming.  I suppose the answer to this is "override the default styles" for your app when necessary, but I just wanted to flag this here if you'd like to make a recommendation for it.

What we did was make the links the same color as text, but keep the underline.  It becomes the red link color on hover. Example: http://dev-discovery.nypl.org/search?q=fire

**Comment by mgiraldo** [comment]
who is giving this feedback?

i do believe that links should be of [different color than normal text](https://www.nngroup.com/articles/guidelines-for-visualizing-links/).

we also need to underline the links (added as issue #10)

if we decide to change the color, what does @ricardoom think? maybe a darker red? maybe use a google-ish blue?

**Comment by ricardoom** [comment]
I think we should use the blue(s) we have already...

**Comment by mgiraldo** [comment]
ok blues then. but still would like to know who is giving this feedback

**Comment by mgiraldo** [comment]
moved to https://github.com/NYPL/design-toolkit/issues/6
