### ISSUE TITLE
$bordercolor variable

### ISSUE THREAD

**Issue by beefoo** [NYPL/design#7]
in _colors.scss ... something like:

```
$bordercolor: $nypllightgray;
```

**Comment by mgiraldo** [comment]
is this a general border? like a separator of two divs? if this is the case, use `$pagetextcolor`.

**Comment by ricardoom** [comment]
@mgiraldo working on this presently.

**Comment by mgiraldo** [comment]
moved to https://github.com/NYPL/design-toolkit/issues/7
