### ISSUE TITLE
Status colors

### ISSUE THREAD

**Issue by beefoo** [NYPL/design#9]
I'm not exactly sure how to generalize this, but for our use-case, we're using colors to reinforce the availability status of an item and the ready-status of a hold request (e.g. green = available or ready).  Note that there can also be a recommendation to "not use colors to indicate/reinforce meaning"

**Comment by mgiraldo** [comment]
do you have an example link for this?

in general we are avoiding relying on color in favor of text (eg: “available”, “not available”). availability can also be reinforced with the presence or absence of buttons.

as we design the request/hold process we can decide if color is required.

**Comment by mgiraldo** [comment]
moved to https://github.com/NYPL/design-toolkit/issues/9
